baseURL = "https://data1030.github.io"
languageCode = "en-us"
title = "DATA 1030"

publishDir = "docs"

[[menu.main]]
weight = 3
name = "Assignments"
url = "/assignment/"

[[menu.main]]
weight = 3
name = "Project"
url = "/project/"


[[menu.main]]
weight = 4
name = "Documents"
url = "/document/"

[[menu.main]]
weight = 5
name = "Calendar"
url = "/calendar/"
