baseURL = "https://data1030.github.io"
languageCode = "en-us"
title = "DATA 1030"

publishDir = "docs"

[[menu.main]]
weight = 3
name = "Assignments"
url = "https://github.com/data1030/course/"

[[menu.main]]
weight = 4
name = "Documents"
url = "https://drive.google.com/open?id=0B5Mwk-2LLWe3T29lejVjUGFLU3c"

[[menu.main]]
weight = 5
name = "Calendar"
url = "/calendar/"
